### ISSUE TITLE
dbmediabd@gmail.comRelease Process for v6.x.x

### ISSUE THREAD

**Issue by LOVAVIET** [PowerShell/PowerShell#11600]
# Release Process for v6.x.x

- [x] Verify that `PowerShell-Native` has been updated/released as needed.
- [x] Check for `PowerShellGet` and `PackageManagement` release plans.
- [x] Start process to sync Azure DevOps artifacts feed such as modules and NuGet packages.
- [x] Create a private branch named `release/v6.x.x` in Azure DevOps repository.
   All release related changes should happen in this branch.
- [x] Prepare packages
    - [x] Kick off coordinated build.
- [x] Kick off Release pipeline.
    - *These tasks are orchestrated by the release pipeline, but here as status to the community.*
    - [x] Prepare packages
        - [x] Sign the RPM package.
        - [x] Install and verify the packages.
        - [x] Trigger the docker staging builds (signing must be done).
    - [x] Create the release tag and push the tag to `PowerShell/PowerShell` repository.
    - [x] Run tests on all supported Linux distributions and publish results.
    - [x] Update documentation, and scripts.
        - [x] Update [CHANGELOG.md](../../CHANGELOG.md) with the finalized change log draft.
        - [x] Stage a PR to master to update other documents and
              scripts to use the new package names, links, and `metadata.json`.
    - [x] For preview releases,
      merge the release branch to GitHub `master` with a merge commit.
    - [x] For non-preview releases,
      make sure all changes are either already in master or have a PR open.
    - [x] Delete the release branch.
    - [x] Trigger the Docker image release.
    - [x] Retain builds.
    - [x] Update https://github.com/dotnet/dotnet-docker/tree/master/3.0/sdk with new version and SHA hashes for global tool.

**Comment by LOVAVIET** [comment]
https://github.com/dotnet/dotnet-docker/tree/master/3.0/sdk

**Comment by LOVAVIET** [comment]
dbmediabd@gmail.com

**Comment by iSazonov** [comment]
Reported to block the user.
