### ISSUE TITLE
Clean up build dependencies

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#1234]
- [ ] Remove unnecessary imports per #521
- [x] Figure out better way to handle "fake" dependencies of ConsoleHost #1477
- [ ] Use SMA reference assembly instead of project for better incremental recompilation
- [ ] Fixup whitespace in new `project.json` files
- [x] Rename `LINUX` to `UNIX` #1483 
- [x] Remove unnecessary package installs in `Start-PSBootstrap` #1279
- [x] Remove hard dependency on PowerShell caused by resgen #1344 
- [x] ~~Ensure optimization is enabled~~
- [ ] Rename build module functions #1233
- [ ] Update manual step documentation
- [x] OS specific modules #1701

**Comment by andschwa** [comment]
This was a meta issue that is no longer required, closing.
