### ISSUE TITLE
Unix usability problems

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#1390]
- [ ] Linux / OS X packages _should_ include default system-wide profiles
- [ ] Path setup for default shell on OS X should work #975
- [ ] Better shebang support #1103 and #992
- [ ] Conflicting PowerShell aliases should be optionally available #3610 
- [x] Removal of unsupported cmdlets from modules #1122 
- [ ] Error handling for native tools, like `set -e`  (need issue)
- [x] Reasonable default colors #1036 
- [x] Proper native pipeline support #559 
- [x] Path normalization of filenames with backslashes #1115
- [x] Path globbing for native commands #954
- [x] Default Emacs keybindings #1388

**Comment by joeyaiello** [comment]
Assigning to myself to triage into the Linux/Mac Usability project.

**Comment by mklement0** [comment]
Re `set -e`: there's an open PR with an RFC: https://github.com/PowerShell/PowerShell-RFC/pull/88

**Comment by joeyaiello** [comment]
Closing this one out as these are all tracked elsewhere (the first one without an issue is made obsolete by #10050).
