### ISSUE TITLE
Fix CA2213: Disposable fields should be disposed

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#15803]
_Tracking issue_: Fix [CA2213: Disposable fields should be disposed](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2213) and remove suppressions.

In #15805, each rule violation will be suppressed like so:
```csharp
#pragma warning disable CA2213 // Disposable fields should be disposed
        private Timer _timer;
#pragma warning restore CA2213 // https://github.com/PowerShell/PowerShell/issues/15803
```

We need to review every case and either fix as bug or suppress with description why it is not bug and maybe add more info in (XML) docs.

Some of the rule violations may be false positives/unfixable/breaking change if the disposable has been injected via a property, etc.

**TODO: after reviewing and fixing all violations listed here, please re-open https://github.com/PowerShell/PowerShell/pull/15805 to enable the CA2213 rule so as to make sure no violations in future.**

## Rule violations

- [ ] 1. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimChildJobBase.cs#L169
- [ ] 2. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L2186
- [ ] 3. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/StreamHelper.cs#L27
- [ ] 4. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/Microsoft.PowerShell.Commands.Utility/commands/utility/XmlCommands.cs#L673
- [ ] 5. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L2981
- [ ] 6. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L2987
- [ ] 7. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/FormatAndOutput/common/BaseCommand.cs#L231
- [ ] 8. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/CommandSearcher.cs#L1069
- [ ] 9. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/CommandSearcher.cs#L1495
- [ ] 10. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/CommandSearcher.cs#L1661
- [ ] 11. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/CommandSearcher.cs#L1666
- [ ] 12. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/DscResourceSearcher.cs#L33
- [ ] 13. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/InternalCommands.cs#L379
- [ ] 14. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/MshCommandRuntime.cs#L2360
- [ ] 15. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/PSClassSearcher.cs#L39
- [ ] 16. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/debugger/debugger.cs#L1692
- [ ] 17. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/hostifaces/ConnectionBase.cs#L688
- [ ] 18. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/hostifaces/ConnectionBase.cs#L989
- [ ] 19. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/hostifaces/PowerShell.cs#L1940
- [ ] 20. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/remoting/client/Job.cs#L3829
- [ ] 21. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/remoting/client/Job2.cs#L529
- [ ] 22. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/remoting/client/remoterunspace.cs#L47
- [ ] 23. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/remoting/client/remoterunspace.cs#L1796
- [ ] 24. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs#L2021
- [ ] 25. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/remoting/commands/ReceiveJob.cs#L317
- [ ] 26. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/remoting/common/RemoteSessionHyperVSocket.cs#L141
- [ ] 27. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/remoting/common/RemoteSessionHyperVSocket.cs#L340
- [ ] 28. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/remoting/common/RemoteSessionNamedPipe.cs#L344
- [ ] 29. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/remoting/common/RemoteSessionNamedPipe.cs#L1010
- [ ] 30. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs#L482
- [ ] 31. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs#L1595
- [ ] 32. https://github.com/PowerShell/PowerShell/blob/a4181ab57eb5f2caafbfc8995a8b1e60622ba43a/src/System.Management.Automation/utils/ObjectReader.cs#L491

**Comment by iSazonov** [comment]
24. InvokeCommandCommand.cs

Invoke-Command calls _steppablePipeline.End() in EndProcessing() where Dispose() is called. So we can suppress the case.

**Comment by iSazonov** [comment]
1. cimChildJobBase.cs

_sleepAndRetryTimer.Dispose() is called in StopJob() and last one is called in Dispose(). So we can suppress the case.

**Comment by iSazonov** [comment]
2. Process.cs

_outputWriter.Dispose(); is called in exit handler StreamClosing(). So we can suppress the case.

**Comment by iSazonov** [comment]
3. WebCmdlet/StreamHelper.cs

_originalStreamToProxy never disposed. It is seem a bug.

**Comment by iSazonov** [comment]
4. XmlCommands.cs

 XmlReader _xr never disposed. It is seem a bug.

**Comment by iSazonov** [comment]
6. ConsoleHost.cs

It seems ConsoleHost i is not responsible for current  pipeline (runningCmd) but remoteRunspace is. No bug.

**Comment by iSazonov** [comment]
5. ConsoleHost.cs

ConsoleTextWriter _consoleWriter is never disposed. It is seem a bug.

**Comment by iSazonov** [comment]
7. BaseCommand.cs

Dispose(); calls in InternalDispose(). So no bug. But perhaps we could use a standard pattern.

**Comment by iSazonov** [comment]
8. CommandSearcher.cs

_matchingCmdlet should be in Dispose(). It is a bug.

**Comment by iSazonov** [comment]
9. CommandSearcher.cs

_pathSearcher is in Dispose(). I wonder why it is alarmed.

**Comment by iSazonov** [comment]
10. CommandSearcher.cs

_matchingAlias should be in Dispose(). It is a bug.

**Comment by iSazonov** [comment]
11. CommandSearcher.cs

_matchingFunctionEnumerator should be in Dispose(). It is a bug.

**Comment by iSazonov** [comment]
12. DscResourceSearcher.cs

_matchingResource = null in Reset() and the Reset is called from Dispose(). It is a bug (we should dispose in Reset()).

**Comment by iSazonov** [comment]
13. InternalCommands.cs

I guess PSTaskChildJob-s  from _taskJob are disposed in ThreadPool but _taskJob itself is never disposed. I think it is bug.

**Comment by iSazonov** [comment]
14. MshCommandRuntime.cs

AllowWrite is not owner of the PipelineProcessor. No bug.

**Comment by iSazonov** [comment]
15. PSClassSearcher.cs

_matchingClass = null in Reset() and the Reset is called from Dispose(). It is a bug (we should dispose in Reset()).

**Comment by iSazonov** [comment]
16. debugger.cs

It seems we could remove _psDebuggerCommand at all - it is used only once in `using` statement.

**Comment by iSazonov** [comment]
17. ConnectionBase.cs

RunspaceOpening  is disposed in LocalConnection.Dispose(). It is not a bug but we could refactor code so that dispose in RunspaceBase.

**Comment by iSazonov** [comment]
18. ConnectionBase.cs

ConnectionBase is not an owner of _currentlyRunningPipeline. It is not a bug. Yes?

**Comment by iSazonov** [comment]
19. PowerShell.cs

It seems PowerShell is not an owner of the _runspacePool.  So no bug.

**Comment by iSazonov** [comment]
20. Job.cs

PSRemotingChildJob is not an owner of the _runspacePool. So no bug.

**Comment by iSazonov** [comment]
21. Job2.cs

ContainerParentJob should dispose _tracer. It is a bug.

**Comment by iSazonov** [comment]
22. remoterunspace.cs

RemoteRunspace is not an owner of the _currentInvokeCommand. So no bug.

**Comment by iSazonov** [comment]
23. remoterunspace.cs

It seems we could remove _psDebuggerCommand at all - it is used only once in `using` statement. Or is there async?

**Comment by iSazonov** [comment]
24. InvokeCommandCommand.cs

Invoke-Command calls _steppablePipeline.End() in EndProcessing() where Dispose() is called. So we can suppress the case.

**Comment by iSazonov** [comment]
25. ReceiveJob.cs

_tracer should be disposed in ReceiveJobCommand.Dispose(). It is a bug.

**Comment by iSazonov** [comment]
26. VSocket.cs

_tracer should be disposed in RemoteSessionHyperVSocketServer.Dispose(). It is a bug.

**Comment by iSazonov** [comment]
27. VSocket.cs

_tracer should be disposed in RemoteSessionHyperVSocketClient.Dispose(). It is a bug.

**Comment by iSazonov** [comment]
28. RemoteSessionNamedPipe.cs

_tracer should be disposed in RemoteSessionNamedPipeServer.Dispose(). It is a bug.

**Comment by iSazonov** [comment]
28. RemoteSessionNamedPipe.cs

_tracer should be disposed in NamedPipeClientBase.Dispose(). It is a bug.

**Comment by iSazonov** [comment]
30. OutOfProcTransportManager.cs

_tracer should be disposed in OutOfProcessClientSessionTransportManagerBase.Dispose(). It is a bug.

**Comment by iSazonov** [comment]
31. OutOfProcTransportManager.cs

_tracer should be disposed in SSHClientSessionTransportManager.Dispose(). It is a bug.

**Comment by iSazonov** [comment]
32. ObjectReader.cs

_enumerator should be disposed in PSDataCollectionReader<T, TResult>.Dispose(). It is a bug.

**Comment by SeeminglyScience** [comment]
WG-Engine discussed this today.

We agree that any valid violation of this rule should be fixed. Leaving as up for grabs.

**Comment by xtqqczze** [comment]
> WG-Engine discussed this today.
> 
> We agree that any valid violation of this rule should be fixed. Leaving as up for grabs.

@iSazonov Please reopen.
