### ISSUE TITLE
disable tracking

### ISSUE THREAD

**Issue by 3052** [PowerShell/PowerShell#21292]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

not sure if its powershell or Windows Terminal, but running the shell I am getting several calls to

https://dc.services.visualstudio.com/v2/track

### Expected behavior

```console
no tracking
```

### Actual behavior

```console
tracking
```

### Environment data

```powershell
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
Have you set [POWERSHELL_TELEMETRY_OPTOUT](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_telemetry?view=powershell-7.4)?

**Comment by 3052** [comment]
$env:POWERSHELL_TELEMETRY_OPTOUT=1 did not fix it

**Comment by 3052** [comment]
$env:POWERSHELL_TELEMETRY_OPTOUT=1 did not fix it

note I also did: Office 365, we could go to File > Options > Trust Center > Trust Center Settings > Privacy Options > View Diagnostic Data > Disable View data viewing.

**Comment by SteveL-MSFT** [comment]
The env var above completely disables AppInsights telemetry as we've documented.  If you are still seeing data being sent, it's not from PowerShell.

**Comment by 3052** [comment]
visualstudio.com is a Microsoft property. could someone please point me in the right direction? I run MITM Proxy for other purposes and I am constantly getting this filling the captured requests

**Comment by mklement0** [comment]
I think that Visual Studio is closed-source, so I assume that your best bet is to use the [Feedback Hub app](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

**Comment by 3052** [comment]
terrible.

**Comment by 3052** [comment]
https://github.com/PowerShell/PowerShell/issues/21508

**Comment by 3052** [comment]
OK I think I fixed it - I was setting POWERSHELL_TELEMETRY_OPTOUT in `Microsoft.PowerShell_profile.ps1`, but it needs to be set BEFORE PowerShell starts:

https://github.com/PowerShell/PowerShell/issues/10005#issuecomment-506076042

shout out to @SteveL-MSFT for failing to mention that
