### ISSUE TITLE
disable tracking

### ISSUE THREAD

**Issue by 3052** [PowerShell/PowerShell#21508]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am posting this again because I think some finger pointing is going on. this is either PowerShell or Windows Terminal, and both groups are refusing to admit cause. when I open Windows Terminal with PowerShell, if I open my network tracking software I see many calls to

https://dc.services.visualstudio.com/v2/track

as soon as I close the terminal window the calls stop. here are the previous issues:

https://github.com/microsoft/terminal/issues/16806
https://github.com/PowerShell/PowerShell/issues/21292

### Expected behavior

I tried these as well:

$env:POWERSHELL_TELEMETRY_OPTOUT=1 
$env:DOTNET_CLI_TELEMETRY_OPTOUT = 1

### Actual behavior

```console
POST /v2/track HTTP/1.1
Host: dc.services.visualstudio.com
Content-Type: application/x-json-stream
Content-Length: 572

{"name":"AppEvents","time":"2024-04-20T12:54:50.1142959Z","iKey":"d26a5ef4-d608-452c-a6b8-a4a55935f70d","tags":
{"ai.cloud.role":"na","ai.cloud.roleInstance":"na","ai.internal.sdkVersion":"dotnetc:2.21.0-429",
"ai.internal.nodeName":"na"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"ConsoleHostStartup",
"properties":{"OSDescription":"Microsoft Windows 10.0.18363","GitCommitID":"7.3.0",
"UUID":"2101c42a-f5e6-47c8-81ae-315f68165568","OSChannel":"unknown","StartMode":"Normal",
"SessionId":"a3e4cd9c-b10f-49c1-b4b7-c03e352e392b"},"measurements":{"Param":8192}}}}

HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
Date: Sat, 20 Apr 2024 12:55:18 GMT

3e
{"itemsReceived":1,"itemsAccepted":1,"appId":null,"errors":[]}
0
```

### Environment data

```powershell
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 3052** [comment]
OK I think I fixed it - I was setting POWERSHELL_TELEMETRY_OPTOUT in `Microsoft.PowerShell_profile.ps1`, but it needs to be set BEFORE PowerShell starts:

https://github.com/PowerShell/PowerShell/issues/10005#issuecomment-506076042
