### ISSUE TITLE
Local spellchecking

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2575]
For incrementally improve #2554.

We are needed local spellchecking:
- [x] .md doc files
- [ ] comments in *.cs files
- [ ] comments in Powershell files *.ps1, *.psm1

It would be good:
 `Start-PSBootstrap`  installed dependencies and  `Start-PSBuild -SpellCheck <filepaths>`  make check.

**Comment by joeyaiello** [comment]
I hope you don't mind I made your list a checklist so that we can track progress on this.

**Comment by iSazonov** [comment]
👍
