### ISSUE TITLE
Improve Copy-Item to provide parity with Robocopy

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#2581]
> Copied from one of the top suggestions on UserVoice: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11087646-implement-native-robocopy-cmdlet

This is a collection of suggestions derived from UserVoice to improve `Copy-Item` so that it's as robust and feature-laden as Robocopy. (Special thanks to everyone in the UserVoice thread. I'm going to try and summarize all your requests as succinctly as possible here.) The bolded items were particularly popular in the UserVoice thread (and I sorted roughly from most to least popular).

Note that there was also some discussion about adding this functionality to a separate cmdlet so as to avoid complicating `Copy-Item` too much. I think there's probably a reasonable balance we can strike here.

- [x] **Deal w/ long paths ([this works now!](https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/))**
- [ ] **Support "retries on failed copies" (`robocopy /R:n /W:n`)**
- [ ] **Support mirroring of a directory tree (`robocopy /MIR`)**
- [ ] **Ability to copy "all file info" (`robocopy /COPYALL`)**
- [ ] **Support excluding certain files and directories (`robocopy /XF foo /XD bar`). (Question: what is needed here that isn't fulfilled by `Copy-Item -Exclude`?)**
- [ ] **Support "backup mode" where any admin can copy items without explicit rights (`robocopy /B`)**
- [ ] Support "restartable mode"/ability to resume file transfers (`robocopy /R`)
- [ ] Support EFS RAW mode to copy encrypted files (`robocopy /EFSRAW`)
- [ ] Support logging to a CSV file (`robocopy /LOG`). (Question: what is not already fulfilled by `ConvertTo-Csv`?)
- [ ] Ability to not overwrite target files that match the source's last write date
- [ ] Support multithreading (`robocopy /MT[:n]`)
- [ ] Support throttling of file transfers for low-bandwidth connections (`robocopy /IPG:n` for "inter-packet gap)
- [ ] Support "copy using unbuffered I/O" (`robocopy /J`)
- [ ] Support arbitrary Robocopy usage (`Copy-Item -Robocopy -RobocopySwitches`) (in my opinion, this isn't a great idea, especially given cross-plat)

**Comment by RobCannon** [comment]
Does long paths work with the shipping version of PowerShell?

**Comment by SteveL-MSFT** [comment]
@RobCannon Windows PowerShell in the Win10 Anniversary Update supports long paths, but you need to enable it for the OS (http://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/?utm_content=buffer5b5de&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer), PowerShell Core supports it by default

**Comment by iSazonov** [comment]
The first question is whether the functionality in core?

It consists of two parts:
1. Interest of the community, I believe that here the answer is Yes.
2. The ability to implement functionality in volume, which will retain the interest of the community. 
To answer the second part we need to do an analysis of what robocopy keys we can effectively implement (considering porting). If the resulting list will be good for the community, then we can go further.

**Comment by Jaykul** [comment]
How about just a `-NoOverwrite` to not overwrite target files, period?

**Comment by rkeithhill** [comment]
I think `-NoClobber` would be more idiomatic.

**Comment by Kriegel** [comment]
I know many, many admins using Robocopy to do backups.

I allways say: if you do not check the integrity of your source <-> destination it is a copy not a backup!

So a verify mechanismm must / should be in the Process. This can be done by a separate cmdlet like Get-FileHash. But this should do it VERY fast and multithreded and IO / Network recource respectful.

So the needs to verify are very similar to Robocopy and they should work together.
So I think it also should be in the Robocopy box.

For Speed reasons i suggest xxHash.
See here for an quick and dirty PowerShell implementation and play with it: https://github.com/Kriegel/PowerHash

**Comment by Kriegel** [comment]
The Runtime Team is discussing a File.CopyAsync method here 
https://github.com/dotnet/runtime/issues/20697
I think @JeremyKuhne is the right guy to ask.

**Comment by juvtib** [comment]
One way to move this forward without waiting for https://github.com/PowerShell/PowerShell/issues/5785 , is to try wrapping robocopy with [Crescendo](https://devblogs.microsoft.com/powershell/announcing-powershell-crescendo-preview-1/).

**Comment by RobCannon** [comment]
But that would not be cross-platform.
