### ISSUE TITLE
Release process tracking for v6.0.0-beta.4 release of PowerShellCore

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#4231]
Release process tracking for Beta.4

- [x] Create a branch named `release` in `PowerShell/PowerShell` repository.
   All release related changes should happen in this branch.
-  [x] Prepare packages
   * [x] [Build release packages](#building-packages).
      - [x] Linux
      - [x] Windows
      - [x] macOS
   * [x] Sign the MSI packages and DEB/RPM packages.
      - [x] Sign Windows MSI packages
      - [x] GPG Sign Linux packages
   * [x] Install and verify the packages.
      - [x] Verify Windows packages
      - [x] Verify Linux packages
      - [x] Verify macOS package

- [x] Update documentation, scripts and Dockerfiles
   * [X] Summarize the change log for the release. It should be reviewed by PM(s) to make it more user-friendly.
   * [x] Update [CHANGELOG.md](../../CHANGELOG.md) with the finalized change log draft.
   * [x] Update other documents and scripts to use the new package names and links.

- [x] Verify the release Dockerfiles.
- [x] [Create NuGet packages](#nuget-packages) and publish them to [powershell-core feed][ps-core-feed].
- [x] [Create the release tag](#release-tag) and push the tag to `PowerShell/PowerShell` repository.
- [x] Create the draft and publish the release in Github.
- [x] Merge the `release` branch to `master` and delete the `release` branch.
- [x] Publish Linux packages to Microsoft YUM/APT repositories.
- [x] Trigger the release docker builds for Linux and Windows container images.
   * [x] Linux: push a branch named `docker` to `powershell/powershell` repository to trigger the build at [powershell docker hub](https://hub.docker.com/r/microsoft/powershell/builds/).
     Delete the `docker` branch once the builds succeed.
   * [x] Windows: queue a new build in `PowerShell Windows Docker Build` on VSTS.
- [x] Verify the generated docker container images.
- [ ] [Update the homebrew formula](#homebrew) for the OSX package.
   This task usually will be taken care of by the community,
   so we can wait for one day or two and see if the homebrew formula has already been updated,
   and only do the update if it hasn't.

**Comment by JoshDoug** [comment]
Just checked and the homebrew cask for beta 4 is available.

**Comment by it-praktyk** [comment]
The link to the CHANGELOG.md ifile s broken in your post.
