### ISSUE TITLE
Clean up test code to use `-Parameter` syntax for Pester tests

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#6245]
Pester documentation for 4.x recommends using `Should -Be` instead of `Should Be` syntax.  We should update all our tests and documentation to adhere to this setting a good example for the community.
- [x] engine #6298                                                                                                               
- [x] Host #6250
- [x] Installer #6250 
- [x] Language #6304
- [x] Modules/CimCmdlets #6306
- [x] Microsoft.PowerShell.Core #6349
- [x] Microsoft.PowerShell.Diagnostics #6351
- [x] Microsoft.Powershell.Host #6250
- [x] Microsoft.PowerShell.LocalAccounts #6499
- [x] Microsoft.PowerShell.Management #6294
- [x] Microsoft.PowerShell.Security #6256
- [x] Microsoft.PowerShell.Utility #6366
- [x] Microsoft.PowerShell.Utility Web #6257                                                                                    
- [x] Microsoft.WSMan.Management #6366
- [x] PackageManagement #6488 
- [x] Modules/PowerShellGet #6488 
- [x] Modules/PSDesiredStateConfiguration #6622 
- [x] Modules/PSReadLine #6488
- [x] Provider #6490
- [x] SDK #6490

**Comment by iSazonov** [comment]
Maybe Meta-Issue? I'd rather break the work apart otherwise we'll get a huge size PR which is hard to review.

**Comment by markekraus** [comment]
hehe I planned to do this with the web cmdlet tests, yes.

**Comment by SteveL-MSFT** [comment]
@iSazonov breaking it up makes sense!

**Comment by bergmeister** [comment]
I haven't tried it yet but [here](https://gist.github.com/indented-automation/aeb14825e39dd8849beee44f681fbab3) is a helper script to upgrade to the new syntax.

**Comment by KevinMarquette** [comment]
I have a PR out for these items on the list:
PowerShellGet, PackageManagement, PSReadLine #6488
SDK and Provider tests #6490

**Comment by KevinMarquette** [comment]
I have a PR out for the LocalAccounts module #6499

**Comment by xtqqczze** [comment]
#6499 was not merged

**Comment by xtqqczze** [comment]
@iSazonov Can you reopen?

**Comment by iSazonov** [comment]
@xtqqczze The Microsoft.PowerShell.LocalAccounts module was removed from PowerShell Core.

**Comment by xtqqczze** [comment]
@iSazonov There is an issue to remplement (#4305) so we should still update pester syntax.

**Comment by iSazonov** [comment]
@xtqqczze It is impossible to get Microsoft.PowerShell.LocalAccounts module based on other API. We have to implement _new_ module and new tests. (See my WIP PR for AccountManagement module)
