### ISSUE TITLE
External blockers

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#667]
Our list of external blockers (that is, things we need other teams to accomplish):

- [x] #656 Remove psl-monad submodule, blocked on #732
- [x] #463 Enable PowerShellGet, blocked on cross-platform availability of OneGet
- [x] #639 Using platform-specific packages, blocked on dotnet/corefx#6743
- [x] #395 `dotnet-resgen` to generate resources
- [x] #746 ~~`dotnet-resgen` to generate C# bindings, blocked on dotnet/cli#819~~ generation implemented in `build.psm1`
- [x] ~~#530 Move content to System.Management.Automation, blocked on dotnet/cli#753~~
- [x] #529 Remove content from superproject, blocked on dotnet/cli#66 or #732 
- [x] #459 Enable DLL strong name verification, blocked on dotnet/cli#720
- [ ] #673 Remove Linux configuration, blocked on dotnet/cli#465
- [ ] #733 Remove the type catalog generator, blocked on dotnet/corefx#1784
- [x] #806 Fix the xUnit runner, blocked on dotnet/cli#2402
- [x] #1211 Native Image Generation

**Comment by andschwa** [comment]
We are getting both the remaining issues with .NET CLI's move to msbuild (which will resolve #673), and .NET Core's next big patch (which will resolve #733), so I'm closing this. Hooray!
