### ISSUE TITLE
Need psl-native library code review

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#6874]
psl-native library appeared at the time of the first version .Net Core 1.0 which had many limitations.
Currently we moved to .Net Core 2.1 and we need to review psl-native library code and remove unneeded p/invokes. Ideally we could remove this library altogether.

TODO Tasks (Please check when it's finished):
- [ ] Remove the native .cpp code related to the changes in #6909 from psl-native
- [ ] Remove the native .cpp code related to the changes in #6948 from psl-native
- [ ] Remove the native .cpp code related to the changes in #6929 from psl-native

**Comment by TravisEz13** [comment]
I reviewed and SetDate is still needed

**Comment by iSazonov** [comment]
We could use other glibc function (without tm struct) to fix SetDate..

**Comment by iSazonov** [comment]
I started reviewing and already found APIs not used. Will push PR.

Some APIs use struct-s and we need review this in depth. We should either use .Net API or fix as recommended by CoreFX team or use another Unix API.

@PaulHigin Can we remove the unused code?
https://github.com/PowerShell/PowerShell/blob/master/src/libpsl-native/src/createprocess.cpp#L79

**Comment by PaulHigin** [comment]
Hi @iSazonov   This is still needed for Linux platforms for SSH remoting.
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs#L2368

We use this native code to create a client SSH process with the needed attributes, and this is not support by DotNet.  Also they indicated they would not support it in the future.

**Comment by TravisEz13** [comment]
@iSazonov I reviewed for structs that cross into managed code and I only found the one and have PR #6881 to fix as DotNet recommended.

**Comment by dantraMSFT** [comment]
psl-native is also needed for syslog and os_log.

**Comment by adityapatwardhan** [comment]
The native code is going to be moved to its own repo: https://github.com/PowerShell/PowerShell-Native

Please make changes here. I am working on creating builds and setting up CI system for it.
