### ISSUE TITLE
Release Process for v6.2.0.rc1

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#8994]
# Release Process for v6.2.0-rc.1

- [x] Verify that `PowerShell-Native` has been updated/released as needed.
- [x] Check for `PowerShellGet` and `PackageManagement` release plans.
- [x] Start process to sync Azure DevOps artifacts feed such as modules and NuGet packages.
- [x] Create a private branch named `release/v6.x.x` in Azure DevOps repository.
   All release related changes should happen in this branch.
- [x] Prepare packages
    - [x] Kick off coordinated build
    - [x] Sign the RPM package.
    - [x] Install and verify the packages.
    - [x] Trigger the docker staging builds (signing must be done.)
- [x] Run tests on all supported Linux distributions and publish results
- [x]  Update documentation, and scripts.
    - [x] Update [CHANGELOG.md](../../CHANGELOG.md) with the finalized change log draft.
    - [x] Stage a PR to master to update other documents and
          scripts to use the new package names, links, and `metadata.json`.
- [x] Kick of Release pipeline
- [x] Create the release tag and push the tag to `PowerShell/PowerShell` repository.
- [x] For preview releases,
  merge the release branch to Github `master` with a merge commit.
- [x] For non-preview releases,
  make sure all changes are either already in master or have
- [x] Delete the release branch.
- [x] Trigger the docker image release.
- [x] Retain builds.

**Comment by TravisEz13** [comment]
```
OS                           Pass Fail Total Skipped Pending
--                           ---- ---- ----- ------- -------
CentOS Linux 7 (Core)        8160    2  9980    1474     344
Debian GNU/Linux 9 (stretch) 8159    2  9980    1475     344
Fedora 28 (Twenty Eight)     8160    2  9980    1474     344
openSUSE Leap 42.3           8160    2  9980    1474     344
Ubuntu 14.04.5 LTS           8158    3  9980    1475     344
Ubuntu 16.04.6 LTS           8146    2  9980    1488     344
Ubuntu 18.04.2 LTS           8146    2  9980    1488     344
```

Per @JamesWTruher 	
> The I've not seen this new error before, but it's in the powershellget feature area. attempting a local repro
the issue did not repro in isolation, there may have been a temporary network issue.

**Comment by adityapatwardhan** [comment]
Release is complete.
