### ISSUE TITLE
Release Process for v6.2.0

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#9224]
# Release Process for v6.2.0

- [x] Verify that `PowerShell-Native` has been updated/released as needed.
- [x] Check for `PowerShellGet` and `PackageManagement` release plans.
- [x] Start process to sync Azure DevOps artifacts feed such as modules and NuGet packages.
- [x] Create a private branch named `release/v6.x.x` in Azure DevOps repository.
   All release related changes should happen in this branch.
- [x] Prepare packages
    - [x] Kick off coordinated build.
    - [x] Sign the RPM package.
    - [x] Install and verify the packages.
    - [x] Trigger the docker staging builds (signing must be done).
- [x] Run tests on all supported Linux distributions and publish results.
- [x] Update documentation, and scripts.
    - [x] Update [CHANGELOG.md](../../CHANGELOG.md) with the finalized change log draft.
    - [x] Stage a PR to master to update other documents and
          scripts to use the new package names, links, and `metadata.json`.
- [x] Kick off Release pipeline.
- [x] Create the release tag and push the tag to `PowerShell/PowerShell` repository.
- [ ] For preview releases,
  merge the release branch to GitHub `master` with a merge commit.
- [x] For non-preview releases,
  make sure all changes are either already in master or have a PR open.
- [x] Delete the release branch.
- [x] Trigger the docker image release.
- [x] Retain builds.

**Comment by TravisEz13** [comment]
Linux test results

```
PS> $r | ft OS,Total,Pass,Fail,Pending,Skipped
OS                           Total Pass Fail Pending Skipped
--                           ----- ---- ---- ------- -------
CentOS Linux 7 (Core)         9996 8183    1     338    1474
Debian GNU/Linux 9 (stretch)  9996 8182    1     338    1475
Fedora 28 (Twenty Eight)      9996 8183    1     338    1474
openSUSE Leap 42.3            9996 8183    1     338    1474
Ubuntu 14.04.6 LTS            9996 8182    1     338    1475
Ubuntu 16.04.6 LTS            9996 8169    1     338    1488
Ubuntu 18.04.2 LTS            9996 8169    1     338    1488
```


expected failure in containers - `Test-Connection.Ping.Force IPv4 with explicit PingOptions`

**Comment by chuanjiao10** [comment]
It seems that it can be released in advance, congratulations in advance by me.

A kind reminder:
Note that the file name  in packages.microsoft.com.
At the time of the release of 6.1, the 6.1.0 GA version was version old than the rc version because of the file name problem, which prevented yum from updating the powershell. Eventually I had to remove the preview package on packages.microsoft.com.
This problem may never appear, it is better.

**Comment by TravisEz13** [comment]
The problem with preview has been fixed since early in 6.1 preview.  The later previews did not have to be removed.  See https://packages.microsoft.com/rhel/7.3/prod/ 
![image](https://user-images.githubusercontent.com/10873629/55181691-60ccae80-5149-11e9-84aa-9e084261867d.png)

**Comment by iSazonov** [comment]
Why ChangeLog is so short for 6.2 release? It seems we skipped most of changes.

**Comment by TravisEz13** [comment]
The changelog we publish here is incremental from the RC release.  I don't think we should put all changes twice in the change log.
